# Copyright 2017 Heptio Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventrouter 
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: eventrouter 
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: eventrouter 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventrouter
subjects:
- kind: ServiceAccount
  name: eventrouter
  namespace: kube-system
---
apiVersion: v1
data:
  config.json: |-
    {
      "sink": "influxdb",
      "influxdbHost": "10.203.181.205:8086",
      "influxdbUsername": "k8s_events",
      "influxdbPassword": "4c9d27af61401461",
      "influxdbName": "k8s_events",
      "influxdbSecure": false,
      "influxdbWithFields": false,
      "influxdbInsecureSsl": false,
      "influxdbRetentionPolicy": "0",
      "influxdbClusterName": "zzzc2",
      "influxdbDisableCounterMetrics": false,
      "influxdbConcurrency": 100
    }
kind: ConfigMap
metadata:
  name: eventrouter-cm-to-influxdb-shbt
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eventrouter-to-influxdb-shbt
  name: eventrouter-to-influxdb-shbt
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eventrouter-to-influxdb-shbt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eventrouter-to-influxdb-shbt
        tier: control-plane-addons
    spec:
      containers:
        - image: r.addops.soft.360.cn/zhenghongfei/eventrouter:v0.3
          imagePullPolicy: Always
          name: kube-eventrouter
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/eventrouter
              name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: eventrouter
      serviceAccountName: eventrouter
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      volumes:
        - configMap:
            defaultMode: 420
            name: eventrouter-cm-to-influxdb-shbt
          name: config-volume
